apiVersion: v1
kind: Service
metadata:
  name: {{ include "gvm.fullname" . }}-gvmd
  labels:
  {{- $_ := set . "applicationNameSuffix" "gvmd" }}
  {{- include "gvm.labels" . | nindent 4 }}
  {{- if .Values.gvmdService.annotations }}
  annotations:
    {{- toYaml .Values.gvmdService.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gvmdService.type }}
  {{- if and .Values.gvmdService.clusterIP (eq .Values.gvmdService.type "ClusterIP") }}
  clusterIP: {{ .Values.gvmdService.clusterIP }}
  {{- end }}
  ports:
    - name: gvmd
      port: {{ .Values.gvmdService.port }}
      targetPort: gvmd
      protocol: TCP
      {{- if (and (eq .Values.gvmdService.type "NodePort") (not (empty .Values.gvmdService.nodePort))) }}
      nodePort: {{ .Values.gvmdService.nodePort }}
      {{- end }}
  {{- if .Values.gvmdService.externalIPs }}
  externalIPs:
    {{- toYaml .Values.gvmdService.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.gvmdService.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.gvmdService.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.gvmdService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.gvmdService.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "gvm.name" . }}-gvmd
    app.kubernetes.io/instance: {{ include "gvm.instance" . }}
